### ISSUE TITLE
AwesomeSocket .Net Standard 2.0 version?

### ISSUE THREAD

**Issue by TheColonel2688** [nterry/AwesomeSockets#15]
Would it be possible to create an AwesomeSockets .Net Standard 2.0 version? Or does Awesome Socket have runtime specific dependencies?

**Comment by nterry** [comment]
@TheColonel2688 I am planning to release a net standard 1.0 version (to be compatible with as many consumers as possible). This is a pure-managed library, so there aren't any weird dependencies at all.

**Comment by TheColonel2688** [comment]
That would be great

**Comment by nterry** [comment]
@TheColonel2688 I deeply apologize for the delay, but I have re-tooled the library to use netstandard 2.0. Use 2.1.18 which has been published to nuget.

**Comment by nterry** [comment]
See #18 for details
