### ISSUE TITLE
Different string encoding between server and client

### ISSUE THREAD

**Issue by EmiyaSyahriel** [nterry/AwesomeSockets#17]
Hi, I tried to send a string data to a server using AwesomeSockets from a non-AwesomeSockets client (due to Xamarin.Android, code partially copied from [Microsoft Docs here](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/asynchronous-client-socket-example)).

I actually uses a simple Bit Scrambling algorithm available in [Here](https://github.com/EmiyaSyahriel/PSWBit6Codec) to scramble the data, still in ASCII though. The server successfully received the string. However, It receives a different string like it was made of Chinese chars.

This is the code I use in client:
```cs
string toBeSend = $"{UserName.Text}\0{PointCount.Text}"; // -> "MyName\01280"
string encodedSend = PSWBit6Codec.Encode(toBeSend); // -> "SWeNXVueBc`p"
byte[] byteData = Encoding.ASCII.GetBytes(encodedSend); 
sendSocket.BeginSend(byteData, 0, byteData.Length, 0, new AsyncCallback(SendCallback), client); 
                          // -> Send "SWeNXVueBc`p" as byte array
```
The code I use in server:
```cs
Buffer recv = Buffer.New();
Buffer.ClearBuffer(recv);
Tuple<int, EndPoint> recvTuple = receiverSocket.ReceiveMessage(recv);
string recvStr = Buffer.Get<string>(recv); // -> It receives "啐坍䍀牄卌恌"
string recvstrREnc = Encoding.ASCII.GetString(Encoding.UTF8.GetBytes(recvStr)); // -> Produces "???????????"
```

What did I miss here? is the Buffer class using a specific encoding when trying to get a string?

**Comment by nterry** [comment]
@EmiyaSyahriel Are you using the same byte order on both machines? Byte order matters with strings... 

https://en.wikipedia.org/wiki/Endianness

**Comment by EmiyaSyahriel** [comment]
Sorry, for leaving this issue open for too long. 
The endianness is not the problem in my case, mainly because of ASCII characters is one byte long and I still get garbled (but different) string with the endian swapping method. It was the `Buffer.Get<string>(Buffer)` itself which combines 2 ASCII `char`s to 1 Unicode `char`.

I've to do a manual re-encoding by getting the buffer `byte[]` and fed it to `Encoding.ASCII.GetBytes` because `BitConverter.ToChar` in `Buffer.GetString`, in most case, reads 2 `byte`s as one Unicode `char`, and this can also led to another problem when it received an odd number of bytes.

Probably you can implement a `GetString(Encoding)` method in the Buffer class?

Here is my extension method to solve my problem in this case:
```
public static string GetString(this AwesomeSockets.Buffers.Buffer it, System.Text.Encoding encoding)
{
    byte[] strData = new byte[0];
    try{
        strData = AwesomeSockets.Buffers.Buffer.GetBuffer(it);
    }catch(System.Exception e){ System.Console.WriteLine($"[E] {e.GetType().Name} : {e.Message}"); }
    return encoding.GetString(strData);
}

//called like 
recv.GetString(System.Text.Encoding.ASCII); // -> finally produced "SWeNXVueBc`p"
```

*P.S : I don't know why the Chinese string in this page have different bytes in them, the bytes I've received during tests were the same, just different final string.*
