### ISSUE TITLE
Compatibility with .NET Core?

### ISSUE THREAD

**Issue by Supergeek** [nterry/AwesomeSockets#9]
error: Package AwesomeSockets 1.4.19 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package AwesomeSockets 1.4.19 supports: net40 (.NETFramework,Version=v4.0)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.1.

Would be great to have a sockets library that works with Core. Not many do yet.

**Comment by nterry** [comment]
Ok, looking into it @Supergeek

**Comment by nterry** [comment]
Done. Version 2.0.6 now supports .net 4.0 and .net core 1.0
